# Generated by Django 3.2.4 on 2022-08-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='fullfilled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
