# Generated by Django 3.2.4 on 2022-09-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='locate_shop',
        ),
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.CharField(max_length=300),
        ),
    ]
