# Generated by Django 3.2.4 on 2022-06-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessforum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogitem',
            options={'ordering': ['-date_posted']},
        ),
        migrations.RenameField(
            model_name='blogitem',
            old_name='creator',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='blogitem',
            old_name='date_created',
            new_name='date_posted',
        ),
        migrations.RemoveField(
            model_name='blogitem',
            name='description',
        ),
        migrations.AddField(
            model_name='blogitem',
            name='content',
            field=models.TextField(null=True, verbose_name='Post Content'),
        ),
    ]
