# Generated by Django 3.2.4 on 2022-04-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='name',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
