# Generated by Django 3.2.4 on 2022-04-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_auto_20220425_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='hits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='investment',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
