# Generated by Django 3.2.4 on 2022-04-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_alter_investment_creater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='name',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
