# Generated by Django 3.2.4 on 2022-04-25 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_alter_investment_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('roi', models.TextField(blank=True, null=True)),
                ('shareholding', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('investment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trading.investment')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
