# Generated by Django 3.2.4 on 2022-04-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0008_investor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='description',
            field=models.TextField(verbose_name='Investment Proposal'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='value',
            field=models.IntegerField(default=0, verbose_name='Funds Pledge'),
        ),
    ]
