# Generated by Django 3.2.4 on 2022-05-04 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0009_auto_20220427_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investment',
            options={'ordering': ['-likes']},
        ),
    ]
