# Generated by Django 3.2.4 on 2022-05-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0010_alter_investment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='investment',
            name='total_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='investment',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='trading.Tag'),
        ),
    ]
