# Generated by Django 3.2.4 on 2022-05-07 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0011_auto_20220507_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
