# Generated by Django 3.2.4 on 2022-05-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0012_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Keywords'),
        ),
    ]
