# Generated by Django 3.2.4 on 2022-05-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0013_alter_investor_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investment',
            options={'ordering': ['-views']},
        ),
        migrations.RemoveField(
            model_name='investment',
            name='hits',
        ),
        migrations.AddField(
            model_name='investment',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Views'),
        ),
    ]
