# Generated by Django 3.2.4 on 2022-05-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0014_auto_20220515_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
