# Generated by Django 3.2.4 on 2022-06-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0015_investment_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='value',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Funds Pledge'),
        ),
    ]
