# Generated by Django 3.2.4 on 2022-06-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0016_alter_investor_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='application_status',
            field=models.CharField(choices=[('pending', 'pending'), ('recieved', 'recieved'), ('verification', 'verification'), ('engagement', 'engagement'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='pending', max_length=64),
        ),
    ]
