# Generated by Django 3.2.4 on 2022-06-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0017_investor_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='closing_date',
            field=models.DateTimeField(null=True),
        ),
    ]
