# Generated by Django 3.2.4 on 2022-06-17 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0024_alter_investment_closing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='closing_date',
            field=models.DateField(default=datetime.date(2022, 8, 16), null=True),
        ),
    ]
