# Generated by Django 3.2.4 on 2022-07-05 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0031_alter_investment_closing_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investor',
            old_name='description',
            new_name='motivation',
        ),
        migrations.AlterField(
            model_name='investment',
            name='closing_date',
            field=models.DateField(default=datetime.date(2022, 9, 3), null=True),
        ),
    ]
