# Generated by Django 3.2.4 on 2022-07-06 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0032_auto_20220705_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='closing_date',
            field=models.DateField(default=datetime.date(2022, 9, 4), null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='motivation',
            field=models.TextField(verbose_name='Investment Motivation'),
        ),
    ]
