# Generated by Django 3.2.4 on 2022-07-20 06:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0034_auto_20220719_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='date_status_changed',
            field=models.DateField(default=datetime.date(2022, 7, 20), null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='closing_date',
            field=models.DateField(default=datetime.date(2022, 9, 18), null=True),
        ),
    ]
