# Generated by Django 3.2.4 on 2022-07-20 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0035_auto_20220720_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='date_status_changed',
            field=models.DateTimeField(default=datetime.date(2022, 7, 20), null=True),
        ),
    ]
