# Generated by Django 3.2.4 on 2022-07-20 15:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0039_alter_investor_date_status_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='application_status',
            field=models.CharField(choices=[('pending', 'pending'), ('recieved', 'recieved'), ('verification', 'verification'), ('accepted', 'accepted'), ('engagement', 'engagement'), ('rejected', 'rejected')], default='pending', max_length=64),
        ),
        migrations.AlterField(
            model_name='investor',
            name='date_status_changed',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 20, 15, 11, 27, 688055, tzinfo=utc)),
        ),
    ]
