# Generated by Django 3.2.4 on 2022-07-20 17:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0040_auto_20220720_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='date_status_changed',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 20, 17, 51, 21, 477975, tzinfo=utc)),
        ),
    ]
