# Generated by Django 3.2.4 on 2022-08-02 14:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0043_auto_20220801_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='closing_date',
            field=models.DateField(default=datetime.date(2022, 10, 1), null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='application_status',
            field=models.CharField(choices=[('pending', 'pending'), ('verification', 'verification'), ('accepted', 'accepted'), ('engagement', 'engagement'), ('rejected', 'rejected')], default='pending', max_length=64),
        ),
        migrations.AlterField(
            model_name='investor',
            name='date_status_changed',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 2, 14, 27, 6, 273733, tzinfo=utc)),
        ),
    ]
