# Generated by Django 3.2.4 on 2022-08-06 10:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0045_auto_20220804_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='closing_date',
            field=models.DateField(default=datetime.date(2022, 10, 5), null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='date_status_changed',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 6, 10, 53, 57, 243513, tzinfo=utc)),
        ),
    ]
