# Generated by Django 3.2.4 on 2022-08-06 14:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0046_auto_20220806_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='weekly_output_target',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='investor',
            name='date_status_changed',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 6, 14, 32, 11, 544229, tzinfo=utc)),
        ),
    ]
