# Generated by Django 3.2.4 on 2022-08-07 06:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trading', '0047_auto_20220806_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='closing_date',
            field=models.DateField(default=datetime.date(2022, 10, 6), null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='date_status_changed',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 7, 6, 9, 28, 701733, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='ProjectOuputGraphPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('g1', models.BooleanField(default=True, verbose_name='G1: 7 day rolling average')),
                ('g2', models.BooleanField(default=True, verbose_name='G2: 14 day average')),
                ('g3', models.BooleanField(default=False, verbose_name='G3: 30 day average')),
                ('g4', models.BooleanField(default=False, verbose_name='G4: 60 day average')),
                ('g5', models.BooleanField(default=False, verbose_name='G5: 120 day average')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_modified'],
            },
        ),
    ]
