# Generated by Django 3.2.4 on 2022-08-07 08:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0048_auto_20220807_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectouputgraphpreference',
            name='g6',
            field=models.BooleanField(default=False, verbose_name='G6: >120 day average'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='date_status_changed',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 7, 8, 42, 5, 31292, tzinfo=utc)),
        ),
    ]
