# Generated by Django 3.2.4 on 2022-08-07 13:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0049_auto_20220807_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='weekly_output_target',
            field=models.IntegerField(default=0, verbose_name='Weekly Inflows Target'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='date_status_changed',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 7, 13, 47, 59, 11590, tzinfo=utc)),
        ),
    ]
