# Generated by Django 3.2.4 on 2022-08-10 09:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0052_auto_20220810_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='date_status_changed',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 10, 9, 10, 45, 870859, tzinfo=utc)),
        ),
    ]
