# Generated by Django 3.2.4 on 2022-08-14 12:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0055_auto_20220814_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='date_status_changed',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 14, 12, 8, 58, 62790, tzinfo=utc)),
        ),
    ]
