# Generated by Django 3.2.4 on 2022-08-16 14:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0060_auto_20220816_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='date_status_changed',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 16, 14, 10, 17, 806710, tzinfo=utc)),
        ),
    ]
