# Generated by Django 3.2.4 on 2022-08-17 05:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0062_auto_20220817_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='date_status_changed',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 17, 5, 23, 32, 892331, tzinfo=utc)),
        ),
    ]
