# Generated by Django 3.2.4 on 2022-08-20 14:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0065_auto_20220820_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='date_status_changed',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 20, 14, 43, 50, 170305, tzinfo=utc)),
        ),
    ]
