# Generated by Django 3.2.4 on 2022-08-21 19:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0067_auto_20220821_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='date_status_changed',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 21, 19, 25, 19, 564148, tzinfo=utc)),
        ),
    ]
