# Generated by Django 3.2.4 on 2022-09-01 01:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0075_auto_20220831_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='closing_date',
            field=models.DateField(default=datetime.date(2022, 10, 31), null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='date_status_changed',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 1, 1, 11, 28, 626186, tzinfo=utc)),
        ),
    ]
