# Generated by Django 3.2.4 on 2022-09-01 11:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0076_auto_20220901_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='date_status_changed',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 1, 11, 37, 50, 908553, tzinfo=utc)),
        ),
    ]
