# Generated by Django 3.2.4 on 2022-09-12 23:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0088_auto_20220913_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='date_status_changed',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 12, 23, 27, 12, 497922, tzinfo=utc)),
        ),
    ]
