# Generated by Django 3.2.4 on 2022-09-16 22:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0095_auto_20220917_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='date_status_changed',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 16, 22, 35, 44, 404101, tzinfo=utc)),
        ),
    ]
