# Generated by Django 3.2.4 on 2022-09-19 05:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0107_auto_20220919_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='date_status_changed',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 5, 45, 19, 217601, tzinfo=utc)),
        ),
    ]
