# Generated by Django 3.2.4 on 2022-09-21 19:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0110_auto_20220921_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='date_status_changed',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 21, 19, 49, 17, 636221, tzinfo=utc)),
        ),
    ]
