# Generated by Django 3.2.4 on 2022-09-22 10:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0112_auto_20220922_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='date_status_changed',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 22, 10, 36, 49, 686012, tzinfo=utc)),
        ),
    ]
