# Generated by Django 3.2.4 on 2022-09-24 11:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0120_auto_20220924_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='date_status_changed',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 24, 11, 40, 41, 649557, tzinfo=utc)),
        ),
    ]
