# Generated by Django 3.2.4 on 2022-09-24 19:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0125_alter_investor_date_status_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='date_status_changed',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 24, 19, 45, 25, 135310, tzinfo=utc)),
        ),
    ]
