# Generated by Django 3.2.4 on 2022-09-25 14:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0127_auto_20220925_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='date_status_changed',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 25, 14, 21, 46, 536213, tzinfo=utc)),
        ),
    ]
