# Generated by Django 3.2.4 on 2022-10-01 13:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0139_auto_20221001_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='date_status_changed',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 1, 13, 52, 35, 491745, tzinfo=utc)),
        ),
    ]
