# Generated by Django 3.2.4 on 2022-10-03 11:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0145_auto_20221003_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='date_status_changed',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 3, 11, 27, 21, 812199, tzinfo=utc)),
        ),
    ]
