# Generated by Django 3.2.4 on 2022-10-05 12:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0149_auto_20221005_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='date_status_changed',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 5, 12, 48, 45, 876925, tzinfo=utc)),
        ),
    ]
