# Generated by Django 3.2.4 on 2022-10-05 20:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0152_alter_investor_date_status_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='date_status_changed',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 5, 20, 39, 39, 814155, tzinfo=utc)),
        ),
    ]
