# Generated by Django 3.2.4 on 2022-10-06 08:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0154_auto_20221006_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='date_status_changed',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 6, 8, 37, 48, 545331, tzinfo=utc)),
        ),
    ]
