# Generated by Django 3.2.4 on 2022-10-13 09:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0162_auto_20221012_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='closing_date',
            field=models.DateField(default=datetime.date(2022, 12, 12), null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='date_status_changed',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 13, 9, 25, 52, 674043, tzinfo=utc)),
        ),
    ]
