# Generated by Django 3.2.4 on 2022-10-13 10:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0163_auto_20221013_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='date_status_changed',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 13, 10, 19, 1, 821701, tzinfo=utc)),
        ),
    ]
