# Generated by Django 3.2.4 on 2022-10-14 19:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0171_auto_20221014_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='date_status_changed',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 14, 19, 24, 9, 560886, tzinfo=utc)),
        ),
    ]
