# Generated by Django 3.2.4 on 2022-10-16 11:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0174_auto_20221016_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='date_status_changed',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 16, 11, 9, 49, 924875, tzinfo=utc)),
        ),
    ]
