# Generated by Django 3.2.4 on 2022-10-17 07:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0177_alter_investor_date_status_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='closing_date',
            field=models.DateField(default=datetime.date(2022, 12, 16), null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='date_status_changed',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 17, 7, 52, 6, 72977, tzinfo=utc)),
        ),
    ]
