# Generated by Django 3.2.4 on 2022-10-17 07:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0178_auto_20221017_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='date_status_changed',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 17, 7, 52, 14, 957238, tzinfo=utc)),
        ),
    ]
