# Generated by Django 3.2.4 on 2022-10-18 15:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0185_auto_20221018_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='date_status_changed',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 18, 15, 19, 45, 683029, tzinfo=utc)),
        ),
    ]
