# Generated by Django 3.2.4 on 2022-10-18 20:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0186_alter_investor_date_status_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='date_status_changed',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 18, 20, 58, 14, 55711, tzinfo=utc)),
        ),
    ]
