# Generated by Django 3.2.4 on 2022-10-19 19:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0188_auto_20221019_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='date_status_changed',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 19, 19, 12, 53, 197180, tzinfo=utc)),
        ),
    ]
