# Generated by Django 3.2.25 on 2026-03-26 02:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0196_auto_20221024_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='closing_date',
            field=models.DateField(default=datetime.date(2026, 5, 25), null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='date_status_changed',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 26, 2, 7, 8, 798896, tzinfo=utc)),
        ),
    ]
