# Generated by Django 3.2.25 on 2026-03-26 12:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0197_auto_20260326_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='date_status_changed',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 26, 12, 24, 31, 682426, tzinfo=utc)),
        ),
    ]
