# Generated by Django 3.2.25 on 2026-03-26 18:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0198_alter_investor_date_status_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='date_status_changed',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 26, 18, 5, 14, 257647, tzinfo=utc)),
        ),
    ]
