# Generated by Django 3.2.4 on 2022-04-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='accessible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='vacancy_type',
            field=models.IntegerField(choices=[(1, 'ENGINEERING'), (2, 'MANAGEMENT'), (3, 'SUPPORT')], default=1),
        ),
    ]
