# Generated by Django 3.2.4 on 2022-04-29 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20220429_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyDuty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('priority', models.IntegerField(default=1)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['priority', 'date_created'],
            },
        ),
        migrations.CreateModel(
            name='VacancySkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('priority', models.IntegerField(default=1)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['priority', 'date_created'],
            },
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['due_date']},
        ),
        migrations.DeleteModel(
            name='VacancyRequirement',
        ),
        migrations.AddField(
            model_name='vacancyskill',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.vacancy'),
        ),
        migrations.AddField(
            model_name='vacancyduty',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.vacancy'),
        ),
    ]
