# Generated by Django 3.2.4 on 2022-04-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20220429_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='email',
            field=models.EmailField(default='hr@gmail.com', max_length=255),
        ),
    ]
