# Generated by Django 3.2.4 on 2022-04-29 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_vacancy_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('priority', models.IntegerField(default=1)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.vacancy')),
            ],
            options={
                'ordering': ['priority', 'date_created'],
            },
        ),
    ]
