# Generated by Django 3.2.4 on 2022-03-21 13:58

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('street', models.CharField(blank=True, max_length=500, null=True)),
                ('city', models.CharField(blank=True, max_length=256, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('zip', models.CharField(blank=True, max_length=12, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('locked', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Company List',
                'verbose_name_plural': 'Company List',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='United States Dollar', max_length=50, unique=True)),
                ('symbol', models.CharField(default='USD', max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ModelCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('description', models.TextField()),
                ('uniqueid', models.CharField(max_length=200, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='model_name')),
                ('status', models.CharField(default='WIP', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('locked', models.BooleanField(default=False)),
                ('simulation_iterations', models.IntegerField(default=1000)),
                ('simulation_run', models.BooleanField(default=False)),
                ('npv_bin_size', models.IntegerField(default=10)),
                ('design_complete', models.BooleanField(default=False)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='investments_appraisal.currency')),
                ('model_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='investments_appraisal.modelcategory', verbose_name='Category')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Model Owner')),
            ],
            options={
                'ordering': ['-last_modified', '-date_created'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='WorkingCapital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accounts_receivable', models.DecimalField(decimal_places=2, default=0.1, max_digits=10)),
                ('accounts_payable', models.DecimalField(decimal_places=2, default=0.1, max_digits=10)),
                ('cash_balance', models.DecimalField(decimal_places=2, default=0.1, max_digits=10)),
                ('usermodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments_appraisal.usermodel')),
            ],
            options={
                'ordering': ['usermodel'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('perpage', models.IntegerField(default=6, verbose_name='Records per page')),
                ('g2', models.BooleanField(default=True, verbose_name='G2: another')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_modified'],
            },
        ),
        migrations.CreateModel(
            name='TimingAssumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_period', models.IntegerField(default=2022)),
                ('construction_start_year', models.IntegerField(default=2022)),
                ('construction_len', models.IntegerField(default=1)),
                ('construction_year_end', models.IntegerField(default=2022)),
                ('operation_start_year', models.IntegerField(default=2023)),
                ('operation_duration', models.IntegerField(default=10)),
                ('operation_end', models.IntegerField(default=2031)),
                ('number_of_months_in_a_year', models.IntegerField(default=12)),
                ('usermodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments_appraisal.usermodel')),
            ],
            options={
                'ordering': ['usermodel'],
            },
        ),
        migrations.CreateModel(
            name='Taxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_duty', models.DecimalField(decimal_places=2, default=0.1, max_digits=10)),
                ('sales_tax', models.DecimalField(decimal_places=2, default=0.25, max_digits=10)),
                ('corporate_income_tax', models.DecimalField(decimal_places=2, default=0.05, max_digits=10)),
                ('usermodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments_appraisal.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Base_Price', max_length=100)),
                ('base_price', models.DecimalField(decimal_places=2, default=1000, max_digits=10)),
                ('change_in_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('usermodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments_appraisal.usermodel')),
            ],
            options={
                'ordering': ['usermodel'],
            },
        ),
        migrations.CreateModel(
            name='MacroeconomicParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_rate_equity', models.DecimalField(decimal_places=2, default=0.12, max_digits=10)),
                ('domestic_inflation_rate', models.DecimalField(decimal_places=2, default=0.1, max_digits=10)),
                ('us_inflation_rate', models.DecimalField(decimal_places=2, default=0.03, max_digits=10)),
                ('exchange_rate', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('dividend_payout_ratio', models.DecimalField(decimal_places=2, default=0.25, max_digits=10)),
                ('num_of_shares', models.IntegerField(default=0)),
                ('investment_costs_over_run_factor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('usermodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments_appraisal.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optionparameters', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, default=1000, max_digits=10), size=6), size=11)),
                ('usermodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments_appraisal.usermodel')),
            ],
            options={
                'ordering': ['usermodel'],
            },
        ),
        migrations.CreateModel(
            name='Financing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_interest_rate', models.DecimalField(decimal_places=2, default=0.05, max_digits=10)),
                ('risk_premium', models.DecimalField(decimal_places=2, default=0.01, max_digits=10)),
                ('num_of_installments', models.IntegerField(default=6)),
                ('grace_period', models.IntegerField(default=1)),
                ('repayment_starts', models.IntegerField(default=2023)),
                ('equity', models.DecimalField(decimal_places=2, default=0.3, max_digits=10)),
                ('senior_debt', models.DecimalField(decimal_places=2, default=0.7, max_digits=10)),
                ('usermodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments_appraisal.usermodel')),
            ],
            options={
                'ordering': ['usermodel'],
            },
        ),
        migrations.CreateModel(
            name='Depreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('economic_life_of_machinery', models.IntegerField(default=20)),
                ('economic_life_of_buildings', models.IntegerField(default=30)),
                ('tax_life_of_machinery', models.IntegerField(default=10)),
                ('tax_life_of_buildings', models.IntegerField(default=10)),
                ('tax_life_of_soft_capital_costs', models.IntegerField(default=3)),
                ('usermodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments_appraisal.usermodel')),
            ],
            options={
                'ordering': ['usermodel'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments_appraisal.currency')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
