# Generated by Django 3.2.4 on 2022-03-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments_appraisal', '0002_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelcategory',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
