# Generated by Django 3.2.4 on 2022-03-29 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investments_appraisal', '0004_newssubscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Downloads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('model_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='investments_appraisal.modelcategory', verbose_name='Category')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Model Owner')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
