# Generated by Django 3.2.4 on 2022-03-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments_appraisal', '0005_downloads'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelcategory',
            name='hits',
            field=models.IntegerField(default=0),
        ),
    ]
