# Generated by Django 3.2.4 on 2022-04-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments_appraisal', '0008_auto_20220403_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='aboutyou',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profession',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
