# Generated by Django 3.2.4 on 2022-04-05 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investments_appraisal', '0009_auto_20220405_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='aboutyou',
            field=models.TextField(blank=True, null=True, verbose_name='About Me'),
        ),
        migrations.CreateModel(
            name='ModelCategoryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.TextField()),
                ('premium', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='investments_appraisal.modelcategory')),
                ('head', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
