# Generated by Django 3.2.4 on 2022-04-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments_appraisal', '0010_auto_20220405_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelcategorydetails',
            name='motto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
