# Generated by Django 3.2.4 on 2022-04-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments_appraisal', '0011_modelcategorydetails_motto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=3500, max_digits=10),
        ),
    ]
