# Generated by Django 3.2.4 on 2022-04-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments_appraisal', '0014_auto_20220416_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='simulation_iterations',
            field=models.IntegerField(default=100),
        ),
    ]
