# Generated by Django 3.2.4 on 2022-04-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments_appraisal', '0016_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_type',
            field=models.IntegerField(choices=[(1, 'PRODUCT_LAUNCH'), (2, 'SYSTEM_UPGRADE'), (3, 'ANOUNCEMENT')], default=1),
        ),
    ]
