# Generated by Django 3.2.4 on 2022-04-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments_appraisal', '0018_alter_events_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='accessible',
            field=models.BooleanField(default=False),
        ),
    ]
