# Generated by Django 3.2.4 on 2022-05-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments_appraisal', '0020_auto_20220420_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='pertable',
            field=models.IntegerField(default=10, verbose_name='Records per table'),
        ),
    ]
