# Generated by Django 3.2.4 on 2022-05-17 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments_appraisal', '0021_userpreference_pertable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financing',
            name='repayment_starts',
        ),
    ]
