# Generated by Django 3.2.4 on 2022-05-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments_appraisal', '0022_remove_financing_repayment_starts'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='description',
            field=models.TextField(default='My own model'),
        ),
    ]
