# Generated by Django 3.2.4 on 2022-05-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments_appraisal', '0023_usermodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='total_params',
            field=models.IntegerField(default=0),
        ),
    ]
