# Generated by Django 3.2.4 on 2022-06-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments_appraisal', '0024_usermodel_total_params'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelcategory',
            options={'ordering': ['-hits']},
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Model Title'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='total_params',
            field=models.IntegerField(default=0, verbose_name='Simulation Params'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='perpage',
            field=models.IntegerField(default=6, verbose_name='Page Records'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='pertable',
            field=models.IntegerField(default=10, verbose_name='Table Records'),
        ),
    ]
