# Generated by Django 3.2.4 on 2022-06-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments_appraisal', '0025_auto_20220603_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='perpage_blogs',
            field=models.IntegerField(default=6, verbose_name='Blogs Page Records'),
        ),
    ]
