# Generated by Django 3.2.4 on 2022-09-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments_appraisal', '0027_usermodel_hits'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
    ]
