# Generated by Django 3.2.25 on 2026-03-26 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments_appraisal', '0028_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timingassumption',
            name='base_period',
            field=models.IntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name='timingassumption',
            name='construction_start_year',
            field=models.IntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name='timingassumption',
            name='construction_year_end',
            field=models.IntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name='timingassumption',
            name='operation_end',
            field=models.IntegerField(default=2035),
        ),
        migrations.AlterField(
            model_name='timingassumption',
            name='operation_start_year',
            field=models.IntegerField(default=2027),
        ),
    ]
