# Generated by Django 3.2.25 on 2026-03-26 18:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments_appraisal', '0029_auto_20260326_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelcategory',
            name='uniqueid',
            field=models.CharField(help_text='Format: [app_name][number]. Examples: **fish001**, **beef011**, **greenhouse008**. This MUST match the exact folder name in your templates directory.', max_length=200, unique=True, validators=[django.core.validators.RegexValidator(message='ID must be lowercase letters and numbers only (e.g., fish001). No spaces, dashes, or symbols.', regex='^[a-z0-9]+$')]),
        ),
    ]
