# Generated by Django 3.2.4 on 2022-03-21 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investments_appraisal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TankDesignParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_tanks', models.IntegerField(default=10)),
                ('tank_length', models.DecimalField(decimal_places=2, default=3.47, max_digits=10)),
                ('tank_width', models.DecimalField(decimal_places=2, default=3.47, max_digits=10)),
                ('depth', models.DecimalField(decimal_places=2, default=0.91, max_digits=10)),
                ('sqm', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('volume_of_water', models.DecimalField(decimal_places=2, default=13285, max_digits=10)),
                ('density_per_cubic_metre', models.DecimalField(decimal_places=2, default=263, max_digits=10)),
                ('total_fish_per_tank_per_cycle', models.IntegerField(default=3000)),
                ('tank_num_of_months_per_cycle', models.IntegerField(default=6)),
                ('fish_per_tank_per_year', models.IntegerField(default=7000)),
                ('usermodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments_appraisal.usermodel')),
            ],
        ),
    ]
