# Generated by Django 3.2.4 on 2022-05-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tankdesignparameters',
            name='building_cost_per_sqm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='tankdesignparameters',
            name='cost_of_land_per_sqm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='tankdesignparameters',
            name='machinery_cost_per_tank',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=15),
        ),
        migrations.AddField(
            model_name='tankdesignparameters',
            name='purchase_price_tank',
            field=models.DecimalField(decimal_places=2, default=700, max_digits=15),
        ),
        migrations.AddField(
            model_name='tankdesignparameters',
            name='total_land_sqm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
