"""
Django settings for demo project.

Generated by 'django-admin startproject' using Django 1.10.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
from pickle import FALSE
from decouple import config, Csv

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.abspath(__file__))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#B99bcw4Tv1h8qn_q5GtB99db0kls8M6avmzu8w8xcd
SECRET_KEY = config('SECRET_KEY')
# Barikoi api key
#BARIKOI_AUTOCOMPLETE_API_KEY = config('BARIKOI_AUTOCOMPLETE_API_KEY')
# SECURITY WARNING: don't run with debug turned on in production!

''' 
You can add an extra argument to the config function, 
to define a default value, in case there is an undefined value in the .env file
By Vitor Freitas, software developer and researcher Brazil

 '''
#DEBUG = config('DEBUG', cast=bool)
DEBUG = config('DEBUG', default=True, cast=bool)
#DEBUG = os.getenv('DEBUG', False) == 'True'
#DEBUG=False
#ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=lambda v: [s.strip() for s in v.split(',')]) 
# or short method hereunder
# |  |
# V  V
ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=Csv())#['*']
SITE_ID = 1

# Application definition

INSTALLED_APPS = [
   
    'whitenoise.runserver_nostatic',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.humanize',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'widget_tweaks',
    'silverstrike',
   
    'allauth',
    'allauth.account',
    #addded 18 Oct 2021
    # 'allauth.socialaccount',
    # 'allauth.socialaccount.providers.google', # for Google OAuth 2.0
    # 'rest_framework',
    # 'rest_framework.authtoken',
    'corsheaders',
     
    
    'django_filters',
    'investments_appraisal.apps.InvestmentsAppraisalConfig',
    'fishapp.apps.FishappConfig',
    'beefapp.apps.BeefappConfig',   
    'import_export',   
    "common",
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', #add whitenoise
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
   
]

CORS_ORIGIN_WHITELIST = (
    'http://localhost:4200',
    'http://127.0.0.1:4200',
)

ROOT_URLCONF = 'myproj.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproj.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': config('DB_NAME'),
#         'USER': config('DB_USER'),
#         'PASSWORD': config('DB_PASSWORD'),
#         'HOST': config('DB_HOST'),
#         'PORT': '',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

 
""" CRISPY_TEMPLATE_PACK = 'bootstrap4'

ASGI_APPLICATION = 'myproj.routing.application'

# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels_redis.core.RedisChannelLayer',
#         'CONFIG': {
#             'hosts': [('127.0.0.1',6379),],
#         }
#     }
# }
 
# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels.layers.InMemoryChannelLayer',
#     },
#     'CONFIG': {
#             "hosts": [('redis',6379)],
#         },
# } 
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'asgi_redis.RedisChannelLayer',
        'CONFIG': {
            'hosts': [('localhost', 6379)],
        },
        'ROUTING': 'myproj.routing.channel_routing',
    }
}

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'django_plotly_dash.finders.DashAssetFinder',
    'django_plotly_dash.finders.DashComponentFinder',
]

PLOTLY_COMPONENTS = [
    'dash_core_components',
    'dash_html_components',
    'dash_renderer',

    'dpd_components',
] 
 
X_FRAME_OPTIONS = 'SAMEORIGIN'

"""

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'


AJAXIMAGE_DIR = 'ajaximage/'
AJAXIMAGE_AUTH_TEST = lambda u: True

LOGIN_REDIRECT_URL = 'index'
LOGIN_URL = 'account_login'
#LOGOUT_URL = 'account_logout'
LOGOUT_URL = 'home_page'
ACCOUNT_LOGOUT_REDIRECT_URL = 'account_login'

# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'static'),
# ]
STATICFILES_DIRS = (BASE_DIR + "/static",)
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

ACCOUNT_EMAIL_VERIFICATION = 'none'#'optional'

''' 

Casting the data
Attention to the cast argument. Django expects DEBUG to be a boolean. 
In a similar way it expects EMAIL_PORT to be an integer.
 '''
#debug only
#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

#-----------to use email uncomment'
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_USE_TLS = True
# EMAIL_HOST = config('EM_HOST') 
# EMAIL_HOST_USER =config('EM_HOST_USER')
# EMAIL_HOST_PASSWORD = config('EM_HOST_PSWD')
# EMAIL_PORT = 587
# EMAIL_PORT = config('EMAIL_PORT', cast=int)
# DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = config('EM_HOST_USER')
EMAIL_HOST_PASSWORD = config('EM_HOST_PSWD')



#uncomment if you want to check all files are collected into staticfile
STATICFILES_STORAGE = 'whitenoise.django.CompressedManifestStaticFilesStorage'
#STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
#STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'

""" 
Added 01 Sept 2021
The recommended way to resolve this is:

During testing, ensure that the STATICFILES_STORAGE setting is set to something else like 'django.contrib.staticfiles.storage.StaticFilesStorage' (the default).

Here's a simple way to do that in your settings.py:
 """
import sys
# print('in Settings:',sys.argv)
# TESTING = len(sys.argv) > 1 and sys.argv[1] == 'test'
# print('TESTING?:',TESTING)

# STATICFILES_STORAGE = (
#     'django.contrib.staticfiles.storage.StaticFilesStorage'
#     if TESTING
#     else 'whitenoise.storage.CompressedManifestStaticFilesStorage'
# )
#STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

WHITENOISE_AUTOREFRESH = True
#this changed everything bus css not loaded in development mode
WHITENOISE_MANIFEST_STRICT = False
# Uncomment to prevent signup
#ACCOUNT_ADAPTER = 'silverstrike.models.SignupDisabledAdapter'

#APPEND_SLASH = False
TIME_INPUT_FORMATS = ['%I:%M %p']
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated'
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication'
    )
}
# LOGGING = {
#     'version': 1,
#     'filters': {
#         'require_debug_true': {
#             '()': 'django.utils.log.RequireDebugTrue',
#         }
#     },
#     'handlers': {
#         'console': {
#             'level': 'DEBUG',
#             'filters': ['require_debug_true'],
#             'class': 'logging.StreamHandler',
#         }
#     },
#     'loggers': {
#         'django': {
#             'handlers': ['console'],
#              'level': os.getenv('DJANGO_LOG_LEVEL', 'DEBUG'),
#         },
#     },
# }

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'ERROR'),
        },
    },
}

# Debugging in heroku live
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': ('%(asctime)s [%(process)d] [%(levelname)s] ' +
                       'pathname=%(pathname)s lineno=%(lineno)s ' +
                       'funcname=%(funcName)s %(message)s'),
            'datefmt': '%Y-%m-%d %H:%M:%S'
        },
        'simple': {
            'format': '%(levelname)s %(message)s'
        }
    },
    'handlers': {
        'null': {
            'level': 'DEBUG',
            'class': 'logging.NullHandler',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose'
        }
    },
    'loggers': {
        'testlogger': {
            'handlers': ['console'],
            'level': 'INFO',
        }
    }
}

DEBUG_PROPAGATE_EXCEPTIONS = True
COMPRESS_ENABLED = os.environ.get('COMPRESS_ENABLED', False)

# Configure Django App for Heroku.
import django_on_heroku
django_on_heroku.settings(locals())
''' 
If you are deploying your application to Heroku using Git, 
you can’t have an .env file in your project root. 
That’s not a problem, because Python Decouple will retreive the environment variables, 
and Heroku let you define those variables on it’s dashboard.

Inside Heroku’s dashboard, first select your app and click on the Settings tab. 
'''

# Error 500 When DEBUG=FALSE ON HEROKU SERVER
""" 
Collectstatic ignores images that are referenced within comment 
but there is a typical behaviour in Django processing 
when Debug=False is set which actually tries to parse and 
verify images within HTML comments (This does not happen when Debug=True is set).

When I removed comments, I was able to render the page and 500 error was gone. 

For what it's worth, you'll face the same issue if you have an html comment in your code that calls the template tag "static" (probably the behavior is the same for every commented template tag), this was my case:

<!-- <img  src="{% static 'main_website/images/image.jpg' %}" alt=""> -->
removing the comment resolved the 500 error (which also, was not being logged).
"""