# Generated by Django 3.2.4 on 2022-04-07 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silverstrike', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='budget',
            name='category',
        ),
        migrations.DeleteModel(
            name='ImportFile',
        ),
        migrations.RemoveField(
            model_name='recurringtransaction',
            name='category',
        ),
        migrations.RemoveField(
            model_name='recurringtransaction',
            name='dst',
        ),
        migrations.RemoveField(
            model_name='recurringtransaction',
            name='src',
        ),
        migrations.RemoveField(
            model_name='split',
            name='account',
        ),
        migrations.RemoveField(
            model_name='split',
            name='category',
        ),
        migrations.RemoveField(
            model_name='split',
            name='opposing_account',
        ),
        migrations.RemoveField(
            model_name='split',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='dst',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='recurrence',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='src',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='RecurringTransaction',
        ),
        migrations.DeleteModel(
            name='Split',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
