# Generated by Django 3.2.4 on 2022-08-10 09:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('dstart', models.DateField(null=True)),
                ('dend', models.DateField(null=True)),
                ('status', models.CharField(max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('target', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('target_complience', models.CharField(default='below', max_length=10)),
                ('note', models.CharField(max_length=500, null=True)),
                ('locked', models.BooleanField(default=False)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.currency')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=10, null=True)),
                ('dstart', models.DateField(null=True)),
                ('dend', models.DateField(null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('salesplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.salesplan')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('basic_salary', models.IntegerField(blank=True, default=10000, null=True)),
                ('bonus', models.FloatField(blank=True, default=0, null=True)),
                ('grade', models.CharField(default='', max_length=15)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Anonymous', 'Anonymous')], default='Male', max_length=10)),
                ('start_date', models.DateField(default=datetime.datetime(2018, 1, 1, 0, 0), verbose_name='Service Entry Date')),
                ('marital_status', models.CharField(choices=[('Married', 'Married'), ('Single', 'Single'), ('Divorced', 'Divorced'), ('Anonymous', 'Anonymous')], default='Married', max_length=10)),
                ('dob', models.DateField(default=datetime.datetime(2000, 1, 1, 0, 0))),
                ('nationality', models.CharField(blank=True, default='Zimbabwean', max_length=20, null=True)),
                ('telephone_no', models.CharField(blank=True, max_length=20, null=True)),
                ('residence_address', models.CharField(blank=True, max_length=50, null=True)),
                ('national_id', models.CharField(blank=True, max_length=20, null=True)),
                ('annual_allowance', models.IntegerField(default=21)),
                ('image_url', models.CharField(default='', max_length=20, null=True)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('title', models.CharField(blank=True, default='Mr.', max_length=10)),
                ('work_station', models.CharField(blank=True, max_length=20, null=True)),
                ('locked', models.BooleanField(default=False)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.currency')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ManyToManyField(blank=True, null=True, to='store.Company')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customers.employee')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company User',
                'verbose_name_plural': 'Company Users',
            },
        ),
    ]
