# Generated by Django 3.2.4 on 2022-05-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beefapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedlotdesignparameters',
            name='building_cost_per_sqm',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=15),
        ),
        migrations.AddField(
            model_name='feedlotdesignparameters',
            name='construction_cost_per_pen',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=15),
        ),
        migrations.AddField(
            model_name='feedlotdesignparameters',
            name='machinery_cost_per_pen',
            field=models.DecimalField(decimal_places=2, default=1200, max_digits=15),
        ),
        migrations.AddField(
            model_name='feedlotdesignparameters',
            name='total_land_sqm',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=15),
        ),
    ]
