# Generated by Django 3.2.4 on 2022-05-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beefapp', '0002_auto_20220519_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedlotdesignparameters',
            name='sqm',
        ),
        migrations.AddField(
            model_name='feedlotdesignparameters',
            name='cost_of_land_per_sqm',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
        ),
    ]
