# Generated by Django 3.2.4 on 2022-05-19 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beefapp', '0003_auto_20220519_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedlotdesignparameters',
            name='cattle_per_pen_per_year',
        ),
        migrations.RemoveField(
            model_name='feedlotdesignparameters',
            name='pen_area',
        ),
    ]
