# Generated by Django 3.2.4 on 2022-05-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beefapp', '0004_auto_20220519_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedlotdesignparameters',
            name='construction_cost_per_pen',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=15),
        ),
    ]
