# Generated by Django 3.2.4 on 2022-08-30 12:23

from django.db import migrations, models
from django.contrib.gis.db.models import PointField
class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', PointField(blank=True, null=True, srid=4326)),
            ],
        ),
    ]
