# Generated by Django 3.2.4 on 2022-09-02 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0002_shop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
