# Generated by Django 3.2.4 on 2022-09-23 07:50

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20220920_1756'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('markers', '0004_worldborder'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(default=None, srid=4326)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['location'],
            },
        ),
        migrations.CreateModel(
            name='TradedCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_expected', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('value', models.IntegerField()),
                ('complete', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('currency_expected', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expected', to='store.currency')),
                ('currency_offered', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offered', to='store.currency')),
                ('residence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='markers.userlocation', verbose_name='location')),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
    ]
