# Generated by Django 3.2.4 on 2022-09-23 08:10

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0006_alter_userlocation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocation',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=None, null=True, srid=4326),
        ),
    ]
