# Generated by Django 3.2.4 on 2022-09-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0007_alter_userlocation_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradedcurrency',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
