# Generated by Django 3.2.4 on 2022-09-23 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0008_alter_tradedcurrency_value'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorldBorder',
        ),
    ]
