# Generated by Django 3.2.4 on 2022-09-24 12:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0009_delete_worldborder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradedcurrency',
            name='residence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residenceA', to='markers.userlocation', verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=None, srid=4326),
        ),
    ]
