# Generated by Django 3.2.4 on 2022-09-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0010_auto_20220924_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradedcurrency',
            name='value',
            field=models.IntegerField(default=0, verbose_name='Offered Value'),
        ),
    ]
