# Generated by Django 3.2.4 on 2022-10-03 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0014_alter_tradedcurrency_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='NearbyDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('distance', models.IntegerField(default=1000)),
                ('source', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nearbyA', to='markers.tradedcurrency')),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
    ]
